# Generated by Django 5.2.8 on 2025-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="NAME", max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, db_column="IMAGE", null=True, upload_to="artists/"
                    ),
                ),
                ("biography", models.TextField(blank=True, db_column="BIOGRAPHY")),
                (
                    "top_musics",
                    models.TextField(
                        db_column="TOP_MUSICS",
                        help_text="Lista de músicas em formato texto (ex.: separadas por vírgula)",
                    ),
                ),
                (
                    "upcoming_shows",
                    models.TextField(
                        db_column="UPCOMING_SHOWS",
                        help_text="Shows futuros; pode ser JSON, texto ou lista formatada",
                    ),
                ),
                (
                    "genre",
                    models.CharField(blank=True, db_column="GENRE", max_length=100),
                ),
                (
                    "country",
                    models.CharField(blank=True, db_column="COUNTRY", max_length=100),
                ),
                ("followers", models.IntegerField(db_column="FOLLOWERS", default=0)),
                (
                    "social_links",
                    models.TextField(
                        blank=True,
                        db_column="SOCIAL_LINKS",
                        help_text="Links de redes sociais em formato texto ou JSON",
                    ),
                ),
            ],
            options={
                "db_table": "Artist",
                "ordering": ["id"],
                "managed": True,
            },
        ),
    ]
